# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoursquareAPIChallenge' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FoursquareAPIChallenge
  
  pod 'Mantle', '~> 2.1'
  pod 'AFNetworking', '~> 3.0'

  target 'FoursquareAPIChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
